### ISSUE TITLE
Project contribution

### ISSUE THREAD

**Issue by diyor28** [rednaks/django-async-orm#14]
Hi there! I love the project and would like to contribute to it! How can I do it?

**Comment by rednaks** [comment]
Hello, thank you for your interest in the project, there is still a lot to do, you can see in the readme all methods that we don't support yet, implement them and write a test. what do you think ? I can assist you if you need help !

**Comment by diyor28** [comment]
Hey there! Sorry for the late reply, I might have missed the notification. Sounds like something I can do! I will then start by implementing one of the unsupported methods and get back to you with a pull request.

**Comment by Archmonger** [comment]
@rednaks I believe this issue can be closed
